insert into Genero (id, nome) values 	(1, 'Não Cadastrado'),
										(2, 'Ação'),
										(3, 'Aventura'),
										(4, 'Animação'),
										(5, 'Comédia'),
										(6, 'Crime'),
										(7, 'Documentário'),
										(8, 'Drama'),
										(9, 'Família'),
										(10, 'Fantasia'),
										(11, 'História'),
										(12, 'Horror'),
										(13, 'Musical'),
										(14, 'Mistério'),
										(15, 'Romance'),
										(16, 'Ficção Científica'),
										(17, 'Filme para TV'),
										(18, 'Suspense'),
										(19, 'Guerra'),
										(20, 'Western');